### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by sduensin** [markwal/OctoPrint-SnapStream#4]
I've installed this onto OctoPi / OctoPrint 1.3.2.  I unchecked the failover box.  I don't see any change in the UI.  mjpg-streamer is still running and chewing up CPU like there's no tomorrow.

**Comment by markwal** [comment]
Oh definitely.  SnapStream uses the snapshot url instead of the stream url.  They both use mjpg-streamer.  SnapStream helps with the browser end that may have trouble with mjpg-streams and/or with bandwidth/routers that may have trouble with the mjpg-stream (people using port forwarding to slow WAN connections).

In fact, with multiple clients, mjpg-streamer used more, not less CPU with SnapStream at high frame rates.
